[package]
name = "x1cz/brainnet2"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
bridgenet2-fork = "ncxyzero/bridgenet2-fork@1.1.5"
luausignal = "ffrostfall/luausignal@0.5.0"